# use_frameworks!
platform :ios, '8.0'

target 'CDSCoreDataSolutions_Example' do
  pod 'CDSCoreDataSolutions', :path => '../'

  target 'CDSCoreDataSolutions_Tests' do
    inherit! :search_paths
    
  end
end
